# Generated by Django 4.0.4 on 2022-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MarketScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gu', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=20)),
                ('dong_code', models.IntegerField()),
                ('service', models.CharField(max_length=10)),
                ('sales_per_mart', models.BigIntegerField()),
                ('run_month', models.IntegerField()),
                ('close_month', models.IntegerField()),
                ('close_rate', models.IntegerField()),
            ],
        ),
    ]
